export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILS = 'USER_REGISTER_FAILS'

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGIN_SUCCESS = 'USER_SIGIN_SUCCESS'
export const USER_SIGIN_FAILS = 'USER_SIGIN_FAILS'